import GuestRegistrationContainer from "@/components/GuestRegistration/GuestRegistration.container";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Guest Registration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GuestRegistrationContainer />
    </>
  );
}
